# Nixpacks configuration for Railway
[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["python3.11 -m pip install -r requirements.txt"]

[phases.build]
cmds = [
    "python3.11 manage.py collectstatic --noinput"
]

[start]
cmd = "python3.11 -m gunicorn config.wsgi --bind 0.0.0.0:$PORT"
